In [2]:
import pandas as pd
import numpy as np

In [3]:
#Load data
df = pd.read_csv('final_data.csv')
df.head()

Reason 1  Reason 2  Reason 3  Reason 4  month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Social smoker  Social drinker  \
0               30          0         2              0               1   
1               31          0         1              0               1   
2               31          0         0              0               1   
3               24          0         2              1               1   
4               30          0         2              0               1   

   Service time  Pets  Absenteeism Time in Hours  
0            13     1                          4  
1            18     0                          0  
2            18     0                          2  
3            14     0                          4  
4            13     1                          2

### Create Target variable
**'Absenteeism time in Hours'** is our target variable, but this has continuos integer type values.

We will make two classes, lets say *'moderately absent'* and *'excessively absent'*

We will first calculate the median of the 'Absenteeism Time in Hours' and use it as a cut-off line.
The hours below median will have a class *'moderately absent'* and the hours above median will have class *'excessively absent'*

In [4]:
df['Absenteeism Time in Hours'].median()

3.0

Any value below 3 is 0 else 1

In [5]:
#Assigning values
targets = np.where(df['Absenteeism Time in Hours'] > df['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
# create a target column 'Excessive Absenteeism'
df['Excessive Absenteeism'] = targets
df.head()

Reason 1  Reason 2  Reason 3  Reason 4  month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Social smoker  Social drinker  \
0               30          0         2              0               1   
1               31          0         1              0               1   
2               31          0         0              0               1   
3               24          0         2              1               1   
4               30          0         2              0               1   

   Service time  Pets  Absenteeism Time in Hours  Excessive Absenteeism  
0            13     1                          4                      1  
1            18     0                          0                      0  
2            18     0                          2                      0  
3            14     0                          4                      1  
4            13     1                          2                      0

### Checking how balance our data is!

In [7]:
targets.sum()/targets.shape[0]

0.45571428571428574

Around 46% of targets are 1s. <br>
For Logistic regression a ratio of 40:60 is fair enough for analysis.

In [8]:
#Drop 'Absenteeism Time in Hours'
df_targets = df.drop(['Absenteeism Time in Hours'], axis = 1)
df_targets.head()

Reason 1  Reason 2  Reason 3  Reason 4  month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Social smoker  Social drinker  \
0               30          0         2              0               1   
1               31          0         1              0               1   
2               31          0         0              0               1   
3               24          0         2              1               1   
4               30          0         2              0               1   

   Service time  Pets  Excessive Absenteeism  
0            13     1                      1  
1            18     0                      0  
2            18     0                      0  
3            14     0                      1  
4            13     1                      0

In [9]:
#remove target variable
unscaled_input_data = df_targets.iloc[:,:-1]
unscaled_input_data.head()

Reason 1  Reason 2  Reason 3  Reason 4  month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Social smoker  Social drinker  \
0               30          0         2              0               1   
1               31          0         1              0               1   
2               31          0         0              0               1   
3               24          0         2              1               1   
4               30          0         2              0               1   

   Service time  Pets  
0            13     1  
1            18     0  
2            18     0  
3            14     0  
4            13     1

### Standardizing Data

In [10]:
#We will not standardize the dummy variables
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy = True, with_mean = True, with_std = True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y = None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y = None, copy = None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns = self.columns)
        X_notScaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_notScaled, X_scaled], axis = 1)[init_col_order]

In [11]:
unscaled_input_data.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'month',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Social smoker', 'Social drinker', 'Service time',
       'Pets'], dtype=object)

In [13]:
columns_to_scale = ['month','Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Service time','Pets']

In [14]:
my_scaler = CustomScaler(columns_to_scale)

In [15]:
#fitting input data
my_scaler.fit(unscaled_input_data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


CustomScaler(columns=['month', 'Day of the Week', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Service time', 'Pets'],
       copy=None, with_mean=None, with_std=None)

In [16]:
#transform
scaled_inputs = my_scaler.transform(unscaled_input_data)
scaled_inputs

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Reason 1  Reason 2  Reason 3  Reason 4     month  Day of the Week  \
0           0         0         0         1  0.182726        -0.683704   
1           0         0         0         0  0.182726        -0.683704   
2           0         0         0         1  0.182726        -0.007725   
3           1         0         0         0  0.182726         0.668253   
4           0         0         0         1  0.182726         0.668253   
5           0         0         0         1  0.182726         1.344231   
6           0         0         0         1  0.182726         1.344231   
7           0         0         0         1  0.182726         1.344231   
8           0         0         1         0  0.182726        -1.359682   
9           0         0         0         1  0.182726        -1.359682   
10          1         0         0         0  0.182726        -1.359682   
11          1         0         0         0  0.182726        -0.683704   
12          1         0         0         0  0.182726        -0.007725   
13          1         0         0         0  0.182726        -0.007725   
14          0         0         0         1  0.182726        -0.007725   
15          1         0         0         0  0.182726         1.344231   
16          0         0         0         1  0.182726         1.344231   
17          0         0         1         0  0.182726        -1.359682   
18          1         0         0         0  0.182726         0.668253   
19          0         0         0         1  0.468236        -0.007725   
20          1         0         0         0  0.468236        -0.007725   
21          1         0         0         0  0.468236        -1.359682   
22          1         0         0         0  0.468236        -1.359682   
23          0         0         0         1  0.468236         1.344231   
24          0         0         1         0  0.468236        -1.359682   
25          0         0         0         1  0.468236        -1.359682   
26          0         0         0         1  0.468236        -0.683704   
27          0         0         0         1  0.468236        -0.007725   
28          0         0         1         0  0.468236        -0.007725   
29          0         0         0         1  0.468236         1.344231   
..        ...       ...       ...       ...       ...              ...   
670         0         0         0         1 -0.673803        -0.683704   
671         0         0         1         0 -0.673803         0.668253   
672         1         0         0         0 -0.673803         0.668253   
673         0         0         0         1 -0.673803         1.344231   
674         0         0         0         1 -0.388293        -1.359682   
675         0         0         1         0 -0.388293        -0.007725   
676         0         0         0         1 -0.388293        -0.007725   
677         1         0         0         0 -0.388293        -0.007725   
678         0         0         0         1 -0.388293        -0.007725   
679         1         0         0         0 -0.388293         0.668253   
680         0         0         0         1 -0.388293         0.668253   
681         1         0         0         0 -0.388293         0.668253   
682         0         0         1         0 -0.388293         1.344231   
683         0         0         0         1 -0.388293         1.344231   
684         0         0         0         1 -0.388293         1.344231   
685         0         0         0         1 -0.388293        -1.359682   
686         1         0         0         0 -0.388293        -0.683704   
687         0         0         0         1 -0.388293        -0.683704   
688         0         0         0         0 -0.388293        -0.683704   
689         0         0         0         1 -0.388293        -0.007725   
690         0         0         0         0 -0.388293        -0.007725   
691         0         1         0         0 -0.388293         1.344231   
692      

In [17]:
scaled_inputs.shape

(700, 17)

### Splitting into training and testing data and shuffling

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [20]:
print(x_train.shape, y_train.shape)

(560, 17) (560,)


In [21]:
print(x_test.shape, y_test.shape)

(140, 17) (140,)


## Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [23]:
reg = LogisticRegression()

In [24]:
reg.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
#find accuracy
reg.score(x_train, y_train)

0.7892857142857143

##### Accuracy is 79%

### Checking accuracy manually

In [26]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [27]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [28]:
model_output == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [29]:
np.sum((model_output == y_train))/ model_output.shape[0]

0.7892857142857143

This is same as the accuracy we calculated before.

### Finding intercept and coefficient

In [30]:
reg.intercept_

array([-1.81785264])

In [31]:
reg.coef_

array([[ 2.62315686,  0.8241172 ,  2.88630304,  0.66513984,  0.15137696,
        -0.07642759,  0.5308533 , -0.05177764, -0.12803928,  0.00418661,
         0.28713403, -0.01929981,  0.32554852,  0.2040058 ,  0.53158227,
        -0.18604935, -0.26579812]])

In [32]:
unscaled_input_data.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'month',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Social smoker', 'Social drinker', 'Service time',
       'Pets'], dtype=object)

In [33]:
feature_names = unscaled_input_data.columns.values

In [34]:
summary_table = pd.DataFrame(columns = ['Feature Name'], data = feature_names)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature Name  Coefficient
0                  Reason 1     2.623157
1                  Reason 2     0.824117
2                  Reason 3     2.886303
3                  Reason 4     0.665140
4                     month     0.151377
5           Day of the Week    -0.076428
6    Transportation Expense     0.530853
7          Distance to Work    -0.051778
8                       Age    -0.128039
9   Daily Work Load Average     0.004187
10          Body Mass Index     0.287134
11                Education    -0.019300
12                 Children     0.325549
13            Social smoker     0.204006
14           Social drinker     0.531582
15             Service time    -0.186049
16                     Pets    -0.265798

In [35]:
#adding intercept to the summary table at first index
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                 Intercept    -1.817853
1                  Reason 1     2.623157
2                  Reason 2     0.824117
3                  Reason 3     2.886303
4                  Reason 4     0.665140
5                     month     0.151377
6           Day of the Week    -0.076428
7    Transportation Expense     0.530853
8          Distance to Work    -0.051778
9                       Age    -0.128039
10  Daily Work Load Average     0.004187
11          Body Mass Index     0.287134
12                Education    -0.019300
13                 Children     0.325549
14            Social smoker     0.204006
15           Social drinker     0.531582
16             Service time    -0.186049
17                     Pets    -0.265798

### Interprete co-efficients

log(odds) = intercept + b1x1 + b2x2 +....................+b14x14 

-0.21  + 2.07 *Reason1 + 0.33 *Reason 2 + 1.56 *Reason3 +...........+(-0.33) * Pets


In [36]:
#finding the corresponding exponential value
summary_table['odd_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature Name  Coefficient  odd_ratio
0                 Intercept    -1.817853   0.162374
1                  Reason 1     2.623157  13.779154
2                  Reason 2     0.824117   2.279867
3                  Reason 3     2.886303  17.926912
4                  Reason 4     0.665140   1.944762
5                     month     0.151377   1.163435
6           Day of the Week    -0.076428   0.926420
7    Transportation Expense     0.530853   1.700383
8          Distance to Work    -0.051778   0.949540
9                       Age    -0.128039   0.879819
10  Daily Work Load Average     0.004187   1.004195
11          Body Mass Index     0.287134   1.332603
12                Education    -0.019300   0.980885
13                 Children     0.325549   1.384790
14            Social smoker     0.204006   1.226305
15           Social drinker     0.531582   1.701623
16             Service time    -0.186049   0.830233
17                     Pets    -0.265798   0.766594

In [37]:
#sort by odd_ratio
#sorting by most relevant co-eff
summary_table.sort_values('odd_ratio', ascending= False)

Feature Name  Coefficient  odd_ratio
3                  Reason 3     2.886303  17.926912
1                  Reason 1     2.623157  13.779154
2                  Reason 2     0.824117   2.279867
4                  Reason 4     0.665140   1.944762
15           Social drinker     0.531582   1.701623
7    Transportation Expense     0.530853   1.700383
13                 Children     0.325549   1.384790
11          Body Mass Index     0.287134   1.332603
14            Social smoker     0.204006   1.226305
5                     month     0.151377   1.163435
10  Daily Work Load Average     0.004187   1.004195
12                Education    -0.019300   0.980885
8          Distance to Work    -0.051778   0.949540
6           Day of the Week    -0.076428   0.926420
9                       Age    -0.128039   0.879819
16             Service time    -0.186049   0.830233
17                     Pets    -0.265798   0.766594
0                 Intercept    -1.817853   0.162374

#### A feature is not relevant if:
1. Its co-efficient is around 0
2. Its odds ratio is around 1

### Baseline model: When no reason is given

-  The odds of being excessively absent after being poisoned are 19 times higher than when NO reason was reported.

### Imp
-  For one std increase in transportation_expense, it is close to twice as likely to be excessively absent(this is the drawback of standardization)
-  Standardized models almost always yield higher accuracy because the optimization algorithms work better.
-  Machine learning engineers prefer models with higher accuracy so they normally go for standardization.
-  economy patricians and statisticians however prefer less accurate but more interpretable models because they care about the underlying reasons behind different phenomena.
-  Data scientists may be in either position sometimes they need higher accuracy. Other times they must find the main drivers of a problem so it makes sense to create two different models one with standardized features and one without them and then draw insights from both. However should we opt for predicting values we definitely prefer higher accuracy so standardization


## Backward Elimination

Remove all features which have close to no contribution to the model.

If the weight(odds ratio) is small enough, remove the feature.

In [38]:
#remove 'Day of the Week', 'Daily Work Load Average' ,'Distance to Work','education'
#
df_new = unscaled_input_data.drop(['Day of the Week', 'Daily Work Load Average' ,'Distance to Work','Education'], axis = 1)
df_new.head()

Reason 1  Reason 2  Reason 3  Reason 4  month  Transportation Expense  Age  \
0         0         0         0         1      7                     289   33   
1         0         0         0         0      7                     118   50   
2         0         0         0         1      7                     179   38   
3         1         0         0         0      7                     279   39   
4         0         0         0         1      7                     289   33   

   Body Mass Index  Children  Social smoker  Social drinker  Service time  \
0               30         2              0               1            13   
1               31         1              0               1            18   
2               31         0              0               1            18   
3               24         2              1               1            14   
4               30         2              0               1            13   

   Pets  
0     1  
1     0  
2     0  
3     0  
4     1

In [39]:
df_new.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Children',
       'Social smoker', 'Social drinker', 'Service time', 'Pets'],
      dtype=object)

In [44]:
new_columns_to_scale = ['month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Children',
        'Service time', 'Pets']

In [45]:
scaler = CustomScaler(new_columns_to_scale)

In [46]:
#fitting new input data
scaler.fit(df_new)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


CustomScaler(columns=['month', 'Transportation Expense', 'Age', 'Body Mass Index', 'Children', 'Service time', 'Pets'],
       copy=None, with_mean=None, with_std=None)

In [48]:
#transform
new_scaled_inputs = scaler.transform(df_new)
new_scaled_inputs

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.


Reason 1  Reason 2  Reason 3  Reason 4     month  Transportation Expense  \
0           0         0         0         1  0.182726                1.005844   
1           0         0         0         0  0.182726               -1.574681   
2           0         0         0         1  0.182726               -0.654143   
3           1         0         0         0  0.182726                0.854936   
4           0         0         0         1  0.182726                1.005844   
5           0         0         0         1  0.182726               -0.654143   
6           0         0         0         1  0.182726                2.092381   
7           0         0         0         1  0.182726                0.568211   
8           0         0         1         0  0.182726               -1.016322   
9           0         0         0         1  0.182726                0.190942   
10          1         0         0         0  0.182726                0.568211   
11          1         0         0         0  0.182726                0.568211   
12          1         0         0         0  0.182726                0.568211   
13          1         0         0         0  0.182726               -0.654143   
14          0         0         0         1  0.182726               -0.654143   
15          1         0         0         0  0.182726                0.356940   
16          0         0         0         1  0.182726               -0.654143   
17          0         0         1         0  0.182726               -0.654143   
18          1         0         0         0  0.182726               -0.503235   
19          0         0         0         1  0.468236                0.387122   
20          1         0         0         0  0.468236                1.624567   
21          1         0         0         0  0.468236               -0.654143   
22          1         0         0         0  0.468236                2.092381   
23          0         0         0         1  0.468236                0.568211   
24          0         0         1         0  0.468236                1.005844   
25          0         0         0         1  0.468236                2.092381   
26          0         0         0         1  0.468236                1.005844   
27          0         0         0         1  0.468236               -0.986140   
28          0         0         1         0  0.468236                1.005844   
29          0         0         0         1  0.468236               -0.654143   
..        ...       ...       ...       ...       ...                     ...   
670         0         0         0         1 -0.673803               -1.016322   
671         0         0         1         0 -0.673803                0.040034   
672         1         0         0         0 -0.673803               -1.574681   
673         0         0         0         1 -0.673803               -0.654143   
674         0         0         0         1 -0.388293                0.190942   
675         0         0         1         0 -0.388293                0.040034   
676         0         0         0         1 -0.388293                0.190942   
677         1         0         0         0 -0.388293               -1.574681   
678         0         0         0         1 -0.388293                0.190942   
679         1         0         0         0 -0.388293               -0.654143   
680         0         0         0         1 -0.388293                1.036026   
681         1         0         0         0 -0.388293                0.040034   
682         0         0         1         0 -0.388293                1.171843   
683         0         0         0         1 -0.388293                0.040034   
684         0         0         0         1 -0.388293               -0.654143   
685         0         0         0         1 -0.388293               -1.574681   
686         1         0         0         0 -0.388293               -1.574681   
687         0         0         0   

In [50]:
#split data
x_train1, x_test1, y_train1, y_test1 = train_test_split(new_scaled_inputs, targets, train_size = 0.8, random_state = 20)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


### Logistic Regression - model 2

In [51]:
reg.fit(x_train1, y_train1)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [52]:
reg.score(x_train1, y_train1)

0.7928571428571428

We can see that removing the features, increased the accuracy to 79.28%.


In [54]:
feature_names = df_new.columns.values
feature_names

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Children',
       'Social smoker', 'Social drinker', 'Service time', 'Pets'],
      dtype=object)

In [55]:


summary_table_new = pd.DataFrame(columns = ['Feature Name'], data = feature_names)

summary_table_new['Coefficient'] = np.transpose(reg.coef_)

summary_table_new


Feature Name  Coefficient
0                 Reason 1     2.623074
1                 Reason 2     0.821454
2                 Reason 3     2.899024
3                 Reason 4     0.645152
4                    month     0.146825
5   Transportation Expense     0.513677
6                      Age    -0.108968
7          Body Mass Index     0.302957
8                 Children     0.316892
9            Social smoker     0.222295
10          Social drinker     0.506883
11            Service time    -0.214716
12                    Pets    -0.269874

In [56]:
#finding the corresponding exponential value
summary_table_new['odd_ratio'] = np.exp(summary_table_new.Coefficient)


In [57]:
summary_table_new.sort_values('odd_ratio', ascending=False)

Feature Name  Coefficient  odd_ratio
2                 Reason 3     2.899024  18.156422
0                 Reason 1     2.623074  13.778014
1                 Reason 2     0.821454   2.273803
3                 Reason 4     0.645152   1.906276
5   Transportation Expense     0.513677   1.671426
10          Social drinker     0.506883   1.660109
8                 Children     0.316892   1.372854
7          Body Mass Index     0.302957   1.353856
9            Social smoker     0.222295   1.248940
4                    month     0.146825   1.158152
6                      Age    -0.108968   0.896759
11            Service time    -0.214716   0.806771
12                    Pets    -0.269874   0.763476

### Testing the model using test data

In [58]:
reg.score(x_test1, y_test1)

0.7428571428571429

#### Based on the data that model has never seen before, the accuracy is 74%.

#### Finding the probability of an output being 0 or 1.

In [59]:
predicted_probability = reg.predict_proba(x_test1)
predicted_probability

#left column: probability of output being 0
#right column: probability of output being 1
#sum of row = 1

array([[0.71236654, 0.28763346],
       [0.55792178, 0.44207822],
       [0.38367346, 0.61632654],
       [0.77595824, 0.22404176],
       [0.07701955, 0.92298045],
       [0.32395474, 0.67604526],
       [0.38052993, 0.61947007],
       [0.17708138, 0.82291862],
       [0.82278196, 0.17721804],
       [0.74546805, 0.25453195],
       [0.39896931, 0.60103069],
       [0.24638197, 0.75361803],
       [0.06699837, 0.93300163],
       [0.76643093, 0.23356907],
       [0.39575249, 0.60424751],
       [0.52446423, 0.47553577],
       [0.45012612, 0.54987388],
       [0.43977354, 0.56022646],
       [0.48415417, 0.51584583],
       [0.05505507, 0.94494493],
       [0.75326638, 0.24673362],
       [0.77595824, 0.22404176],
       [0.4275258 , 0.5724742 ],
       [0.4275258 , 0.5724742 ],
       [0.3006252 , 0.6993748 ],
       [0.79013014, 0.20986986],
       [0.45613192, 0.54386808],
       [0.85432409, 0.14567591],
       [0.20636666, 0.79363334],
       [0.77595824, 0.22404176],
       [0.

#### Let us only focus on probability of getting 1 i.e. excessive absenteeism

In [60]:
predicted_probability[:,1]

array([0.28763346, 0.44207822, 0.61632654, 0.22404176, 0.92298045,
       0.67604526, 0.61947007, 0.82291862, 0.17721804, 0.25453195,
       0.60103069, 0.75361803, 0.93300163, 0.23356907, 0.60424751,
       0.47553577, 0.54987388, 0.56022646, 0.51584583, 0.94494493,
       0.24673362, 0.22404176, 0.5724742 , 0.5724742 , 0.6993748 ,
       0.20986986, 0.54386808, 0.14567591, 0.79363334, 0.22404176,
       0.4012133 , 0.62865527, 0.69412943, 0.62095453, 0.22404176,
       0.54232826, 0.1834134 , 0.75978243, 0.32791624, 0.6237806 ,
       0.21683846, 0.46845087, 0.19630501, 0.46517512, 0.63032111,
       0.55787508, 0.72299706, 0.28763346, 0.22358593, 0.20980414,
       0.58291624, 0.38944488, 0.67604526, 0.27024702, 0.85134516,
       0.46284567, 0.91774638, 0.2572205 , 0.43659155, 0.44692899,
       0.71472282, 0.66679754, 0.31712301, 0.74152749, 0.1544361 ,
       0.2707648 , 0.19253086, 0.1834134 , 0.73282098, 0.26491319,
       0.1834134 , 0.27944028, 0.92370798, 0.37565678, 0.60377

## Saving the model

‘pickle’ is the standard Python tool for serialization and deserialization. In simple words, pickling means: converting a Python object (no matter what) into a string of characters. Logically, unpickling is about converting a string of characters (that has been pickled) into a Python object.

In [61]:
import pickle

In [62]:
#wb: write byte
#model: file name

with open('model','wb') as file:
    pickle.dump(reg, file)

In [63]:

with open('scaler','wb') as file:
    pickle.dump(scaler, file)